services:
  parse:
    container_name: "parse"
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - TOKEN = ${{ secrets.github_token }}
        - USERNAME = ${{ github.actor }}
    env_file:
      - .env
    environment:
        - GITHUB_TOKEN=${{ secrets.github_token }}
        - GITHUB_USERNAME=${{ secrets.actor }}

    ports:
      - "8081:8080"
    volumes:
      - parse_data:/app/data

volumes:
  parse_data:
    driver: local
