services:
  parse:
    container_name: "parse"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    volumes:
      - parse_data:/app/data


volumes:
  parse_data:
    driver: local
