version: '3.8'

services:
  parse:
    container_name: "parse-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
