version: '3.8'

services:
  parse:
    container_name: "parse-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      DB_HOST: db_parse
      DB_PORT: 5432
      DB_NAME: parse-db
      DB_USER: sa
      DB_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
