name: Continuous Integration

on:
  workflow_call:
    secrets:
      PAT_TOKEN:
        description: 'Personal Access Token'
        required: true

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Build and Test
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: ./gradlew build
