name: Master Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  continuous-integration:
    name: Continuous Integration
    uses: ./.github/workflows/CI.yml
    secrets:
      token: ${{ secrets.TOKEN }}

  continuous-delivery:
    name: Continuous Delivery
    needs: continuous-integration
    uses: ./.github/workflows/publish-and-update.yml
    with:
      registry: ghcr.io
      image_name: teamverdeingsis/parse:latest
      actor: ${{ secrets.USERNAME }}
      host: ${{ github.ref_name == 'main' && '172.179.233.92' || '4.242.32.158' }}
      user: teamVerde1
      container_name: 'printscript-api'
    secrets:
      token: ${{ secrets.TOKEN }}
      key: ${{ secrets.SSH_PRIVATE_KEY }}

