name: Master Workflow

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  continuous-integration:
    name: Continuous Integration
    uses: ./.github/workflows/CI.yml
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN}}

  continuous-delivery:
    name: Continuous Delivery
    needs: continuous-integration
    uses: ./.github/workflows/publish-and-update.yml
    with:
      registry: ghcr.io
      image_name: teamverdeingsis/parse:latest
      actor: ${{ github.actor }}
      host: ${{ github.ref_name == 'main' && '172.179.233.92' || '4.242.32.158' }}
      user: teamVerde1
      container_name: 'parse-service-infra'
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN}}
      key: ${{ secrets.SSH_PRIVATE_KEY}}
